### ISSUE TITLE
Question about max threshold of 25 in setCutoffs

### ISSUE THREAD

**Issue by amilesj** [JamesStimson/transcluster#1]
Hello,

I am trying out transcluster (it's working well so far!) and have a question: is there reasoning behind the choice of setting a max of 25 transmissions in the setCutoffs function, or was that pretty much an arbitrary choice? I'm just curious if that max is driven by what seems relevant in an outbreak scenario, or if it has more to do with how the model behaves as the samples get more genetically distant.

Thanks,
Arianna

**Comment by JamesStimson** [comment]
Hi Arianna,
Apologies for not pickup up on this at the time.
It is set at a level which is likely to be above any likely relevant cut off for an outbreak. It is there in order to avoid lengthly calculations when they are unlikely to be needed. But ideally they should be default settings in all parts of the code, which should be controlled by the user. I am reviewing the code as I don't think that is currently the case everywhere in the code!
James

**Comment by amilesj** [comment]
Got it, thanks!
